### PR TITLE
Add script for automatic papers download

### PR DESCRIPTION
**Pull request by mjanv**
Hello,

I'd like to propose a Python script for automatic download of all the papers listed in the README. It works properly on the current list for HTML and PDF links. It downloads all the documents into a folder tree (located at ```pdfs/```) following the structure given by the Markdown headers of the ```README.md``` file

The only file not working is the Github link to the Deep Learning Book.

The script has been tested with Python 2.7.10 on MacOS. The script with a bit of tweaking should work with 2.7 and 3.0+.

I provide all the necessary into ```download.py```. ```requirements.txt``` is useful to setup the right environnement using the commands.
```
virtualenv --python=2.7 py
source py/bin/activate
pip install -r requirements.txt
python download.py
```

Is that something that can be useful to the project ? 
If yes, I will improve the script which remains quite basic for now.

### CODE REVIEW

**Comment by songrotek** [comment]
This is awesome!
 But still there are two problems:
1, When the roadmap updates, how to update only download the new papers instead of re-download once.
2, when a link is failed to download (maybe the network problem), the script would report error and could not download next paper.

Wish you could solve these two problems!

**Comment by mjanv** [comment]
Ok. Cool! :smiley:  

 That was proof of a concept to see if you were interested by this. As you are, I can improve with:

- Better ruling for links (What to do in case of a arxiv link, Github link, html,...)
- A few options through ```argparse```:
    - **--directory**: where to put the directory
    - **--no-html**: don't download HTML pages
    - ...
- Automatic handling of download failure
- Better tree navigation

For the overwriting when the roadmap updates, I don't really have a plan/solution right now. It may be not as simple as it seems to be. If anyone have a suggestion, I'm up for ideas! :bulb: 

For example, what happens if you had a paper into a subsection in first position, so all the papers are moved by one rank, there will be duplicates into the addition of the two trees ? What if a section is renamed ? ... ?

I will push the first items into this pull request when I will be done with them.

**Comment by mjanv** [comment]
Ok, new features.

* You can use the function with some arguments:
    - **-d \<directory\>**: to define the output directory
    - **--no-html**: don't download link with html extension
    - **--overwrite**: if output directory already exists, delete it beforehand
    ```
    python download.py -d otherfolder --no-html --overwrite
    ```
* If any type of exception is catched during the download of a link, it pass to the next one. The failures are kept into memory and displayed at the end.
* Better (ie shorter) display of titles into the console.

**Comment by songrotek** [comment]
Good Job！ I Merge it first, and you can update to perfect the script with other people's opinions.

**Pull request merged**
